### ISSUE TITLE
Get error

### ISSUE THREAD

**Issue by rinkujain43** [AuthorizeNet/sample-code-php#35]
Hello,

I downloaded this code and trying to use in localhost but i was getting an warning that is "Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in C:\wamp\www\samplemaster\test-runner.php on line 2". So where i can fond this vendore DIR and the file autoload.php.

**Comment by ashtru** [comment]
Did you try running composer update in the root directory? For which, [composer](https://getcomposer.org/doc/00-intro.md) should be installed.

**Comment by ashtru** [comment]
Did you get the issue resolved?

**Comment by rinkujain43** [comment]
No I don't. After installation it need the php path.

On Wed, Mar 16, 2016 at 6:37 PM, Ashutosh Singh <notifications@github.com>
wrote:

> Did you get the issue resolved?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AuthorizeNet/sample-code-php/issues/35#issuecomment-197316493>
>



-- 
Thanks & Regards
Rinku Jain
mob.- 9755317077

**Comment by ashtru** [comment]
For composer?
You need to point it to the php directory e.g. C:\php or C:\Program Files\php
You don't need any server (xampp, wamp, or IIS), you only need command-line php.

**Comment by ashtru** [comment]
or you can point it to the folder where your php.ini is inside wamp.

**Comment by ashtru** [comment]
But since you are not supposed see this output in a browser. 
My final suggestion is;
 Install a command-line php like php5.6 non-thread (from [here](http://windows.php.net/download/)) in e.g. C:\php-5.6.14-Win32-VC11-x86
Install composer, pointing this php folder.
Open a windows command prompt in root folder of sample-code-php
*composer update*
*php PaymentTransactions\charge-credit-card.php*

*Also Note:  You cannot run php charge-credit-card.php from sample-code-php\PaymentTransactions folder. *

**Comment by adavidw** [comment]
In the absence of any further questions, I'll close this issue for now. Please let us know if you need any more information or help.
