### ISSUE TITLE
Doctrine errors related to PHP version

### ISSUE THREAD

**Issue by mrbobbybryant** [AuthorizeNet/sample-code-php#99]
When running the example here: https://github.com/AuthorizeNet/sample-code-php/blob/master/PaymentTransactions/authorize-credit-card.php

I get the following error:
```Fatal error: Uncaught TypeError: Return value of Doctrine\Common\Annotations\AnnotationRegistry::registerFile() must be an instance of Doctrine\Common\Annotations\void, none returned```

It looks like you require `goetas-webservices/xsd2php-runtime` which then requires `jms/serializer` which then uses `doctrine/annotations`. 

Dotrine/annotations now requires PHP 7.1. Does that mean that your library will only work in PHP 7.1? I upgraded my version to 7.1 and the process did in fact work. Please let me know if all of the info above is correct. Seems like your docs would need to be updated to say `7.1` instead of `5.6`.

Thank You.

**Comment by adavidw** [comment]
Hi @mrbobbybryant,

Our SDK still only requires PHP 5.6. It's only annotations >=1.5.0 that require PHP7. 1.4.0 works just fine on PHP 5.6 or PHP 7.

When you install our SDK, we always recommend running composer to ensure that the dependency packages are all there and are all the correct versions. I think you already know all this, but for the benefit of all watching, I'll walk through the process here.

In the case of this sample code repo, our composer.json requires authorizenet/authorizenet ^1.9.3. So, running `composer update` or `composer install` on a PHP 5.6 installation should install version 1.9.3 of authorizenet/authorizenet. That's the latest release version, and the info in packagist indicates it's appropriate for PHP 5.6.

- The composer.json for authorizenet/authorizenet 1.9.3 requires goetas-webservices/xsd2php-runtime ^0.2.2 (among other things). That requirement should be fullfilled by version 0.2.7 of that package.
- That goetas-webservices/xsd2php-runtime package in turn requires jms/serializer ^1.2. jms/serializer 1.9.1 is the latest version and is acceptable on PHP 5.6, so that should be installed.
- jms/serializer 1.9.1 requires doctrine/annotations ^1.0. Here's where composer has to make a decision. There's a 1.5.0 version available, but that requires PHP 7.1. Composer should ignore that since the PHP version is 5.6, and move to the next newest version, which is 1.4.0, and is appropriate for PHP 5.6

So, if you're using PHP 5.6 and got doctrine/annotations 1.5.0 installed, something bad happened during that above process. Either you didn't actually use composer to install the dependencies or composer itself somehow fell down on the job, or something else happened.

Some problems I've seen occasionally are that someone will install the sample code repo under one PHP version, but then later move the whole directory to another machine with a different version of PHP and not rerun composer. Another fairly common problem is when you have a different version of PHP on the command line than that run by the web server. If you installed the sample code repo using PHP 7 on the command line, but then attempted to run the samples through the web server (which was using PHP 5.6), you'd run into problems with dependencies with the wrong versions.

Not saying you did any of these things, mind you. Those are just something I've seen occasionally. But, to sum up, there should be no problem running this code under versions of PHP <7.1 _as long as you run composer and it does its job_.
